language: ruby

rvm:
  - 2.6.0

services:
  - postgresql

install:
  - bundle install --jobs 3 --retry 3
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails assets:precompile
  - bundle exec rails test