language: ruby

rvm:
  - 2.6.0

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  bundle install — jobs=3 — retry=3 \
  bundle exec rails db:create \
  bundle exec rails db:migrate \
  bundle exec rails test